require 'custom.keymaps.autogenerated'

local harpoon_status_ok, harpoon = pcall(require, 'harpoon')

if harpoon_status_ok then
  -- REQUIRED
  harpoon:setup()
  -- REQUIRED

  vim.keymap.set('n', '<C-f>', function()
    harpoon.ui:toggle_quick_menu(harpoon:list())
  end, {
    desc = 'Toggle harpoon quick menu',
  })

  vim.keymap.set('n', '<C-b>', function()
    harpoon:list():add()
  end, {
    desc = 'Add file to harpoon',
  })

  vim.keymap.set('n', ']h', function()
    harpoon:list():next()
  end, {
    desc = 'Next [h]arpoon file',
  })

  vim.keymap.set('n', '[h', function()
    harpoon:list():prev()
  end, {
    desc = 'Prev [h]arpoon file',
  })

  for i = 1, 6 do
    vim.keymap.set('n', '<leader>' .. i, function()
      harpoon:list():select(i)
    end, { desc = '[' .. i .. '] Mark' })
  end
end

vim.keymap.set('n', 'ZQ', '<cmd>qa<CR>', { desc = 'Quit all buffers' })

vim.keymap.set('n', '<leader>v', '<cmd>vsplit | lua vim.lsp.buf.definition()<CR>', { desc = '[v]ertical Split Definition' })

vim.keymap.set('n', '<C-s>', '<cmd>w<CR>', { desc = '[s]ave' })

vim.keymap.set('v', '.', '<cmd>normal .<CR>', { desc = '[d]ot command over visual block' })

vim.keymap.set('v', '<leader>p', '"_dP', { desc = '[p]aste without yanking' })

vim.keymap.set('n', 'yoe', function()
  vim.cmd('set eventignore=' .. (vim.o.eventignore == '' and 'all' or ''))
  print(vim.o.eventignore == '' and 'Eventignore OFF' or 'Eventignore ON')
end, { desc = '[e]ventignore' })

vim.keymap.set('n', 'yoss', '<cmd>setlocal spell!<CR>', { desc = '[s]pelling Toggle' })
vim.keymap.set('n', 'yosp', '<cmd>setlocal spell! spelllang=pl<CR>', { desc = '[p]olish' })
vim.keymap.set('n', 'yose', '<cmd>setlocal spell! spelllang=en<CR>', { desc = '[e]nglish' })

-- jumplist every 5 lines jump with j/k
vim.keymap.set('n', 'k', 'v:count > 5 ? "m\'" .. v:count .. "k" : "k"', { expr = true, silent = true })
vim.keymap.set('n', 'j', 'v:count > 5 ? "m\'" .. v:count .. "j" : "j"', { expr = true, silent = true })

vim.keymap.set('c', 'w!!', 'execute "silent! write !sudo tee % >/dev/null" <bar> edit!', { desc = '[w]rite as sudo[!!]' })
-- emacs keybinds in command line mode
vim.keymap.set('c', '<C-a>', '<Home>')
vim.keymap.set('c', '<C-e>', '<End>')
vim.keymap.set('c', '<C-f>', '<Right>')
vim.keymap.set('c', '<C-b>', '<Left>')

vim.keymap.set('n', 'Y', 'y$', { desc = '[Y]ank to the end' })

vim.keymap.set('n', '<A-h>', ':vertical resize +2<CR>')
vim.keymap.set('n', '<A-j>', ':resize -2<CR>')
vim.keymap.set('n', '<A-k>', ':resize +2<CR>')
vim.keymap.set('n', '<A-l>', ':vertical resize -2<CR>')
vim.keymap.set('n', '<C-Left>', ':vertical resize +2<CR>')
vim.keymap.set('n', '<C-Down>', ':resize -2<CR>')
vim.keymap.set('n', '<C-Up>', ':resize +2<CR>')
vim.keymap.set('n', '<A-Right>', ':vertical resize -2<CR>')

vim.keymap.set('t', '<C-h>', '<C-\\><C-N><C-w>h')
vim.keymap.set('t', '<C-j>', '<C-\\><C-N><C-w>j')
vim.keymap.set('t', '<C-k>', '<C-\\><C-N><C-w>k')
vim.keymap.set('t', '<C-l>', '<C-\\><C-N><C-w>l')

vim.keymap.set('n', '<leader>cs', '<C-w>s:term<CR>', { desc = '[h]orizontal' })
vim.keymap.set('n', '<leader>cv', '<C-w>v:term<CR>', { desc = '[v]ertical' })
vim.keymap.set('n', '<leader>ct', '<cmd>silent !tmux neww tmux-sessionizer<CR>', { desc = '[t]mux Session' })

vim.keymap.set('n', '<leader>tn', '<cmd>tabnew<CR>', { desc = '[n]ew' })
vim.keymap.set('n', '<leader>tc', '<cmd>tabclose<CR>', { desc = '[c]lose' })
vim.keymap.set('n', '<leader>to', '<cmd>tabonly<CR>', { desc = '[o]nly' })
vim.keymap.set('n', '<leader>tm', ':tabmove', { desc = '[m]ove' })
vim.keymap.set('n', '<leader>te', ":tabedit <C-r>=expand('%:p:h')<CR>/", { desc = '[e]dit' })
vim.keymap.set('n', '<leader>tt', '<cmd>tabnew<CR><cmd>term<CR><cmd>setlocal nonumber norelativenumber<CR>', { desc = '[t]erminal' })

vim.keymap.set('n', '<leader>pl', '<cmd>Lazy<cr>', { desc = '[l]azy' })
vim.keymap.set('n', '<leader>pi', '<cmd>Lazy install<cr>', { desc = '[i]nstall' })
vim.keymap.set('n', '<leader>ps', '<cmd>Lazy sync<cr>', { desc = '[s]ync' })
vim.keymap.set('n', '<leader>pp', '<cmd>Lazy profile<cr>', { desc = '[p]rofile' })
vim.keymap.set('n', '<leader>pr', '<cmd>Lazy restore<cr>', { desc = '[r]estore' })
